// kicad-canvas — GENERATED SOURCE MODULE (split from the former static/kicad-canvas.js; static/kicad-canvas.js is now the esbuild output of web/canvas/index.ts — edit these modules, not the bundle).
// @ts-nocheck — moved verbatim from the original module; typing is being tightened module by module
import { buildGeom } from "./geom";
import { has, isList, kid, kids, num, parse, str, uuidOf } from "./sexpr";
import { KICAD_BASE_VERSION } from "./version";
// ---------------------------------------------------------------- documents
export function newDoc(type) {
  return { type, items: new Map(), lib: new Map(), page: PAPER_SIZES.A4.slice(), layers: new Map(), copper: [], bbox: null, nets: new Map(), version: 0,
    // drawing-sheet context (web/canvas/sheet.ts): the paper's KiCad name (${PAPER}), the (title_block …)
    // fields, and the sheet identity the app fills in — fileName / filePath / sheetName / sheetPath /
    // pageNumber / sheetCount — so the title block resolves the same variables eeschema does.
    paper: "A4", portrait: false, titleBlock: {}, pageNumber: "1", sheetCount: 1,
    fileName: "", filePath: "", fileRoot: "", sheetName: "", sheetPath: "", projectName: "", projectVars: null,
    // GetBaseVersion() for this tree (web/canvas/version.ts, regenerated by scripts/gen-version.js):
    // ${KICAD_VERSION} reads "KiCad E.D.A. " + this, exactly as ds_painter.cpp:119-121 formats it.
    kicadVersion: KICAD_BASE_VERSION };
}

// PAGE_INFO::standardPageSizes (common/page_info.cpp:42-63); every entry is landscape, `portrait` swaps.
// KiCad stores every page as a whole number of MILS, and the metric papers go through the MMsize()
// macro — EDA_UNIT_UTILS::Mm2mils = KiROUND(mm * 1000 / 25.4) (common/eda_units.cpp:72) — so A4 is
// 11693 x 8268 mils = 297.0022 x 210.0072 mm, not the nominal 297 x 210.  The difference is only
// 2-11 um, but the drawing sheet anchors to the page's right and bottom corners, so using the
// nominal value displaces every frame, tick, rule and title-block coordinate on the page and, on
// A3/A2, keeps a tick that KiCad's IsInsidePage drops (410 > 419.989 - 10).
export const MM_PER_MIL = 25.4 / 1000;
export const mm2mils = (mm) => Math.round(mm * 1000 / 25.4);          // EDA_UNIT_UTILS::Mm2mils
export const milsPage = (w, h) => [w * MM_PER_MIL, h * MM_PER_MIL];   // whole mils -> mm
const mmPage = (w, h) => milsPage(mm2mils(w), mm2mils(h));            // MMsize()
const userMm = (mm) => Math.max(mm, 10 * MM_PER_MIL);                 // clampWidth/clampHeight
export const PAPER_SIZES = { A5: mmPage(210, 148), A4: mmPage(297, 210), A3: mmPage(420, 297), A2: mmPage(594, 420), A1: mmPage(841, 594), A0: mmPage(1189, 841),
  A: milsPage(11000, 8500), B: milsPage(17000, 11000), C: milsPage(22000, 17000), D: milsPage(34000, 22000), E: milsPage(44000, 34000),
  GERBER: milsPage(32000, 32000), USLetter: milsPage(11000, 8500), USLegal: milsPage(14000, 8500), USLedger: milsPage(17000, 11000) };

export function paperSize(node) {
  const name = str(node[1]);
  const sizes = PAPER_SIZES;
  // A custom page keeps its mm exactly: SetWidthMM feeds SetWidthMils a *double* (include/page_info.h:136),
  // so unlike the standard papers it is not rounded to whole mils — only clamped to 10 mils
  // (common/page_info.cpp:175-190).
  let s = sizes[name] || (name === "User" ? [userMm(num(node[2], 297)), userMm(num(node[3], 210))] : PAPER_SIZES.A4);
  if (has(node, "portrait")) s = [s[1], s[0]];
  return s.slice();
}


/**
 * (title_block (title …) (date …) (rev …) (company …) (comment N "…")) — the fields
 * TITLE_BLOCK::TextVarResolver answers (common/title_block.cpp:122-190).
 */
export function titleBlockOf(node) {
  const tb = {};
  for (const c of node.slice(1)) {
    if (!isList(c)) continue;
    if (c[0] === "comment") tb["comment" + num(c[1], 0)] = str(c[2]);
    else if (c[0] === "title" || c[0] === "date" || c[0] === "rev" || c[0] === "company") tb[c[0]] = str(c[1]);
  }
  return tb;
}


export function parseDoc(text, docType) {
  const tree = parse(text);
  if (!tree) throw new Error("not an s-expression document");
  const type = tree[0] === "kicad_sch" ? "sch" : tree[0] === "kicad_pcb" ? "pcb" : (docType === "kicad_sch" ? "sch" : "pcb");
  const doc = newDoc(type);
  if (type === "sch") { const ls = kid(tree, "lib_symbols"); if (ls) for (const s of kids(ls, "symbol")) doc.lib.set(str(s[1]), s); }
  for (let j = 1; j < tree.length; j++) {
    const node = tree[j]; if (!isList(node)) continue;
    const k = node[0];
    if (k === "paper") { doc.page = paperSize(node); doc.paper = str(node[1]) || "A4"; doc.portrait = doc.page[1] > doc.page[0]; }
    else if (k === "title_block") { doc.titleBlock = titleBlockOf(node); continue; }
    else if (k === "sheet_instances") { const p = kid(node, "path"); const pg = p && kid(p, "page"); if (pg) doc.pageNumber = str(pg[1]) || "1"; continue; }
    else if (k === "version") { doc.version = num(node[1], 0); continue; }   // echoed back on every fragment we send
    else if (type === "pcb" && k === "layers") {
      // (0 "F.Cu" signal ["user name"])
      for (const l of node.slice(1)) if (isList(l)) { const name = str(l[1]), ltype = str(l[2]); doc.layers.set(name, { id: num(l[0]), type: ltype, userName: l[3] !== undefined ? str(l[3]) : "" }); if (/\.Cu$/.test(name) && ltype !== "user") doc.copper.push(name); }
    }
    else if (k === "net") { if (type === "pcb") doc.nets.set(num(node[1], -1), str(node[2])); continue; }   // (net 3 "GND"): the board's net table
    else if (k === "lib_symbols" || k === "generator" || k === "generator_version" || k === "general" || k === "setup" || k === "symbol_instances" || k === "embedded_fonts" || k === "embedded_files" || k === "uuid") continue;
    else addItem(doc, node);
  }
  computeBBox(doc);
  return doc;
}


// Every item token either editor can write.  A kind missing here is not merely unrendered:
// addItem() returns null, so a peer's op for it is dropped without a trace and the two
// views diverge silently.  The trailing kinds have no geometry builder yet — they are
// carried so ops for them still match, and so a document round-trip does not lose them.
export const SCH_KINDS = new Set(["symbol", "wire", "bus", "junction", "label", "global_label", "hierarchical_label", "netclass_flag", "directive_label", "no_connect", "sheet", "text", "text_box", "polyline", "rectangle", "circle", "arc", "bezier", "bus_entry", "image", "table", "rule_area",
  "ellipse", "ellipse_arc", "net_chain"]);

export const PCB_KINDS = new Set(["footprint", "segment", "arc", "via", "zone", "gr_line", "gr_rect", "gr_circle", "gr_arc", "gr_poly", "gr_text", "gr_text_box", "gr_curve", "gr_bbox", "dimension", "target", "image", "group", "table", "generated",
  "gr_ellipse", "gr_ellipse_arc", "barcode", "point", "grid_item"]);


export function addItem(doc, node) {
  const k = node[0];
  if (doc.type === "sch" ? !SCH_KINDS.has(k) : !PCB_KINDS.has(k)) return null;
  let id = uuidOf(node);
  if (!id) id = "anon-" + (doc.items.size + 1) + "-" + Math.random().toString(36).slice(2, 8);
  const item = { id, kind: k, node, geom: [], bbox: null, movable: false, hiddenGeom: null, docType: doc.type };
  buildGeom(doc, item);
  doc.items.set(id, item);
  return item;
}


export function computeBBox(doc) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  const take = (b) => { if (!b) return; x0 = Math.min(x0, b[0]); y0 = Math.min(y0, b[1]); x1 = Math.max(x1, b[2]); y1 = Math.max(y1, b[3]); };
  if (doc.type === "pcb") {
    // What a person means by "the board": the outline together with the copper.
    for (const it of doc.items.values()) if (it.edge || it.kind === "segment" || it.kind === "via" || it.kind === "footprint" || it.kind === "zone" || it.kind === "arc") take(it.bbox);
    if (!isFinite(x0)) for (const it of doc.items.values()) take(it.bbox);
  } else {
    x0 = 0; y0 = 0; x1 = doc.page[0]; y1 = doc.page[1];
  }
  doc.bbox = isFinite(x0) ? [x0, y0, x1, y1] : [0, 0, doc.page[0], doc.page[1]];
}
