// editor — GENERATED SOURCE MODULE (split from the former static/app.js; static/dist/editor.js is the esbuild output of web/editor/index.ts — edit these modules, not the bundle).
// @ts-nocheck
/** The editor's mutable state — every former top-level `let` of the original script, referenced as E.<name>. */
export const E: any = {
  toastN: 0,
  ws: null,
  retries: 0,
  canJoin: false,
  viewOnly: false,
  myClientId: "",
  wsToken: "",
  IU: 1e6,
  vbPerMm: 1,
  DOC_TYPE: "kicad_pcb",
  ITEM_TYPE: "FOOTPRINT",
  sheets: [],
  vb: [0, 0, 297, 210],
  items: [],
  selected: null,
  drag: null,
  pan: null,
  zoom: 1,
  panX: 0,
  panY: 0,
  tool: "select",
  editsSeen: 0,
  opN: 0,
  lastPresence: 0,
  lastLiveMove: 0,
  followPeer: null,
  suppressBreakout: false,
  peerState: {},
  comments: [],
  openThread: null,
  layers: {},
  renderTimer: 0,
  renderDirtySince: 0,
  baseVersion: 0,
  kdoc: null,
  hiddenLayers: new Set(),
  layersSeeded: false,
  gridOn: true,
  snapOn: true,
  gridPitch: 1.27,
  localOrigin: [0, 0],
  lastCursorMm: [0, 0],
  polarCoords: false,
  crosshairMode: "small",
  renderOpts: {},
  measure: null,
  zoomRect: null,
  activeLayer: "",
  markers: [],
  proSettings: null,
  selection: new Set(),
  selMode: "rect",
  boxSel: null,
  highlightIds: null,
  selField: null,
  fdrag: null,
  renderReq: 0,
  lastStageW: 0,
  viewTouched: false,
  lastFpHit: null,
  connectGen: 0,
  panes: {},
  units: "mm",
};
(typeof window !== "undefined" ? window : globalThis)["CollabEditor"] = E;
