#!/usr/bin/env node
// Writes web/canvas/version.ts — the KiCad version the web editor reports as its own, so the title
// block's ${KICAD_VERSION} cell reads what the desktop built from this tree reads.
//
// KiCad resolves ${KICAD_VERSION} to `productName + " " + GetBaseVersion()`
// (common/drawing_sheet/ds_painter.cpp:40,119-121), and GetBaseVersion() returns the KICAD_VERSION
// macro from the generated build/kicad_build_version.h (common/build_version.cpp:96).  This mirrors
// CreateGitVersionHeader.cmake's own chain, best source first:
//   1. build/kicad_build_version.h — the exact string the desktop binary in this tree was compiled
//      with, so a side-by-side comparison matches to the character;
//   2. `git describe --dirty` — what a fresh cmake configure would write (CreateGitVersionHeader.cmake:31-75);
//   3. cmake/KiCadVersion.cmake's KICAD_SEMANTIC_VERSION — cmake's own fallback when git is absent.
const fs = require("fs"), path = require("path"), { execFileSync } = require("child_process");

const repo = path.resolve(__dirname, "..", "..");
const out = path.join(repo, "server", "web", "canvas", "version.ts");

function fromHeader() {
  try {
    const t = fs.readFileSync(path.join(repo, "build", "kicad_build_version.h"), "utf8");
    const m = /^#define\s+KICAD_VERSION\s+"([^"]*)"/m.exec(t);
    return m && m[1] ? m[1] : null;
  } catch { return null; }
}
function fromGit() {
  try { return execFileSync("git", ["describe", "--dirty"], { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim() || null; }
  catch { return null; }
}
function fromCmake() {
  try {
    const t = fs.readFileSync(path.join(repo, "cmake", "KiCadVersion.cmake"), "utf8");
    const m = /set\(\s*KICAD_SEMANTIC_VERSION\s+"([^"]*)"\s*\)/.exec(t);
    return m && m[1] ? m[1] : null;
  } catch { return null; }
}

const version = fromHeader() || fromGit() || fromCmake() || "";
const body = `// GENERATED by 'node scripts/gen-version.js' (run from 'npm run build') — do not edit.
//
// GetBaseVersion() (common/build_version.cpp:96): the KICAD_VERSION the KiCad in this tree is built
// with.  ${"$"}{KICAD_VERSION} in a drawing sheet's title block is "KiCad E.D.A. " + this.
export const KICAD_BASE_VERSION = ${JSON.stringify(version)};
`;
let old = ""; try { old = fs.readFileSync(out, "utf8"); } catch { /* first run */ }
if (old !== body) fs.writeFileSync(out, body);
process.stdout.write("KICAD_BASE_VERSION = " + JSON.stringify(version) + "\n");
